language: swift
osx_image: xcode9

branches:
 only:
 - master

 env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script:
  - set -o pipefail
  - xcodebuild -project SKRadioButton.xcodeproj -scheme SKRadioButton -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c